services:
  dev-db:
    image: postgres:13
    ports:
      - 5434:5432
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - prismadata:/var/lib/postgresql/data

  app:
    restart: always
    container_name: main
    image: nestjs-project-app:latest # this will overwrite the existing image, if image was there
    build: 
      context: .
      dockerfile: Dockerfile
    command: yarn start:dev
    ports:
      - 3000:3000
    env_file:
      - .env
    environment:
      DATABASE_URL: ${DATABASE_URL_DOCKER}
      JWT_SECRET: ${JWT_SECRET}
    depends_on:
      - dev-db
volumes :
  prismadata: