name: Run Database Container For e2e-test cases

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-postgres-container:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        ports:
          - 5434:5432
        options: >-
          --name prisma-test-db
          --health-cmd "pg_isready -U testuser"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        env:
          POSTGRES_USER: testuser
          POSTGRES_PASSWORD: testpass
          POSTGRES_DB: test_db

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Wait for Postgres to be ready
        run: |
          echo "Waiting for Postgres to be ready..."
          until pg_isready -h localhost -p 5434 -U testuser; do
            sleep 1
          done
          echo "Postgres is ready! But no further actions are taken."

