name: Run Database Container For e2e-test cases

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  start-container:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: ${{secrets.DB_USER_TEST}}
          POSTGRES_PASSWORD: ${{secrets.DB_PASSWORD_TEST}}
          POSTGRES_DB: ${{secrets.DB_NAME_TEST}}
        ports:
          - 5434:5432
        options: >-
          --health-cmd="pg_isready -U $${secrets.DB_USER_TEST}"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Wait for Postgres to be ready
        run: |
          echo "Waiting for Postgres to be ready..."
          until pg_isready -h localhost -p 5434 -U testuser; do
            sleep 1
          done
          echo "Postgres is ready! But no further actions are taken."

