name: Run Database Container For e2e-test cases

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  start-container:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: ${{secrets.DB_USER_TEST}}
          POSTGRES_PASSWORD: ${{secrets.DB_PASSWORD_TEST}}
          POSTGRES_DB: ${{secrets.DB_NAME_TEST}}
        ports:
          - 5434:5432
        options: >-
          --health-cmd="pg_isready -U dummy_user"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Wait for Container Health Check
        run: |
          echo "Postgres container is up and running. Doing nothing else..."
